name: tenmoku_coins
description: An app for coin collectors

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ## draw is the redit API wrapper
  draw: ^0.9.1
  google_fonts: ^1.1.1
  ## dio is an http client for dart
  dio: ^3.0.10

  uuid: ^2.2.2
  ## for launching a URL on mobile
  url_launcher: ^6.0.0-nullsafety.1
  ## App/Deep Links (Android) and Universal Links and Custom URL schemes (iOS).
  uni_links: ^0.4.0

  flutter_bloc: ^6.1.1
  equatable: ^2.0.0-nullsafety.0

  ## used for formatting dates and times (and other things)
  intl: ^0.17.0-nullsafety.2

  ## The following adds the Cupertino Icons font to your application.
  ## Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1+1

  ## Attractive logging
  logger: ^0.9.4

  ## Used for filter chips
  chips_choice: ^2.0.1

  ## Used for the tags in lists to show matchces
  badges: ^1.1.4

  ## Wraps platform-specific persistent storage for simple data
  shared_preferences: <2.0.0

  ## cross-platform widgets
  flutter_platform_widgets: ^0.71.0

  ## This package provides a library that performs static analysis of Dart code.
  ## It is useful for tool integration and embedding.
  analyzer: ^0.41.0

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
#  assets:


